config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'application#home'
  resources :orders
  resources :items
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # has_and_belongs_to_many :orders
  has_many :orders
  
  # has_many :items, through: orders:
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :order_items, through: :orders

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :items, through: :order_items

  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def home

  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create

    @customer = Customer.create(customer_params)
    redirect_to customer_path(@customer)
  end


  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    if @customer.save
      @customer.save
      redirect_to customer_path(@customer)
    else
      redirect_to edit_customer_path(@customer)
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end


  private

  def customer_params
    params.require(:customer).permit(:name, :phone)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.create(item_params)
  end

  def new
    @item = Item.new

  end

  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item)
  end
  def destroy
    if @item
      @item.destroy
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :ordered_from, :size, :description)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.create(order_params)
  end

  def new

  end

  def edit
    @order = Order.find(params[:id])
    @order.update(order_params)
  end

  def destroy
    if @order
      @order.destroy
    end
  end

  private

  def order_params
    params.require(:orders).permit(:status, :customer_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/application/home.html.erb
<div class="centered">
  <%= link_to "Create a new Customer", new_customer_path %>
  <br />
  <br />
  <%= link_to "New Order", new_order_path %>
</div>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>

<%= f.label :name %>
<br />
<%= f.text_field :name %>
<br />
<%= f.label :phone %>
<br />
<%= f.text_field :phone %>
<br />
<%= f.submit "Submit" %>
<% end %>

app/views/customers/index.html.erb
<% @customers.each do |c| %>
  <%=link_to "#{c.name}", customer_path(c) %>
  <br />
<% end %>

app/views/customers/new.html.erb
<%= form_for(@customer) do |f| %>

<%= f.label :name %>
<br />
<%= f.text_field :name %>
<br />
<%= f.label :phone %>
<br />
<%= f.text_field :phone %>
<br />
<%= f.submit "Submit" %>
<% end %>

app/views/customers/show.html.erb
<h1> Customer Details</h1>
<br />
<br />
<br />
<p>Name: <%=@customer.name%></p>
<br />
<p>Phone: <%=@customer.phone%></p>

<%=link_to "Edit", edit_customer_path(@customer) %>
<%= link_to "Delete", @customer, :method => :delete %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>

<%= f.label :name %>
<br />
<%= f.text_field :name %>
<br />
<%= f.label :ordered_from %>
<br />
<%= f.text_field :ordered_from %>
<br />
<%= f.label :size %>
<br />
<%= f.text_field :size %>
<br />
<%= f.label :description %>
<br />
<%= f.text_field :description %>

<br />
<%= f.submit "Submit" %>
<% end %>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <p><%= item.name %></p>
  <p><%= item.size %></p>
  <p><%= item.description %></p>
  <br />
  <%= link_to "Edit", edit_item_path(item) %>
  <%= link_to "Delete", @item, :method => :delete %>
  <hr />

  <% end %>

app/views/items/show.html.erb
<p><%= @item.name %></p>
<p><%= @item.ordered_from %></p>
<p><%= @item.size %></p>
<p><%= @item.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<!-- <%= form_for @order do |f| %>
<%= f.label : -->

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<% @orders.each do |o| %>
  <%=link_to o.customer.name, order_path(o.id) %>
<% end %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<div class="centered">
  <h1>Order Status</h1>
  <br />
  <br />
  <br />

  <h4>Customer Name: <%= @order.customer.name %></h4>
  <h4>Customer phone: <%= @order.customer.phone %></h4>

  <h4>Order Date: <%= @order.created_at %></h4>
  <% if @order.items.length == 0 %>
    <p>There are no items in this order </p>
  <% else %>
    <% @order.items.each_with_index do |item, index| %>
      <p><%= index+1 %>. <%= item.name%>  <%=item.ordered_from%></p>
    <% end %>
  <% end %>
  <br />


</div>